### ISSUE TITLE
Map 1 for milestone 4 report

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#24]
- [x] WBR boundary, 
- [x] WB dist boundary
- [x] birdlife boundary 
- [x] tertiary catchments - ensure these stand out: Matlabas/Mokolo; Lephalala; Mogalakwena
  - [x] rivers
- [x] protected areas
- [x] proposed study boundary
- [x] topography (shaded relief)
- [x] roads, towns etc (from OSM basemap should be fine)

**Comment by gubuntu** [comment]
@seabilwe do you have the birdlife boundary? If so, where is it?

The point is not to create a QGIS project but to define the SEMP project extent as the UNION of all the above features that intersect with the WBR

Please move the habitat map to a separate issue

**Comment by seabilwe** [comment]
@gubuntu Here is the study area
![image](https://user-images.githubusercontent.com/56301949/91735536-bc0b9780-ebac-11ea-90d4-63e5690da7e7.png)

**Comment by gubuntu** [comment]
have you sent it to Richard? Please send cc me, showing the features used to compose it too.

**Comment by seabilwe** [comment]
No, not yet

I used the IBA, and Tertiary catchments to compose the study area boundary.

Here are the rivers in the catchment
![Rivers](https://user-images.githubusercontent.com/56301949/91799108-a76be580-ec26-11ea-8877-db61b8982958.JPG)

**Comment by gubuntu** [comment]
The map needs to show the boundary, rivers, district, catchments, IBA, using defaults styles from PostGIS ideally, styled so the AOI stands out and you can make out the other layers. Proibably no polygon fill and with rivers on top

**Comment by seabilwe** [comment]
Okay, will improve on that

**Comment by seabilwe** [comment]
@gubuntu here are the improved maps

![report 1](https://user-images.githubusercontent.com/56301949/91943828-7ca09080-ecfd-11ea-86c7-81585e5edc54.JPG)

Without river and IBA
![report 2](https://user-images.githubusercontent.com/56301949/91943834-7e6a5400-ecfd-11ea-9b98-0f865e649970.JPG)

**Comment by gubuntu** [comment]
Better...This and the other maps should be done as layouts with all the usual map elements - remember, they are to go into a report. 

The district boundary is not clear, nor are river names. It needs to be one map showing all the elements I mentioned above

**Comment by seabilwe** [comment]
@gubuntu 
Oh yes, I had already done that on Layout... I was taking screengrabs as I was going through the maps

Alright I'll make them more visible

**Comment by gubuntu** [comment]
rather post the output of exporting the ayout as a png/jpg than a screengrab.
